"""add authenticated

Revision ID: 34fcd5e30126
Revises: 686307b6e072
Create Date: 2021-03-29 22:28:17.610643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fcd5e30126'
down_revision = '686307b6e072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
