"""add precipitation

Revision ID: 686307b6e072
Revises: ea140b0a0ff1
Create Date: 2021-03-29 17:49:55.393613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686307b6e072'
down_revision = 'ea140b0a0ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'precipitation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('precipitation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
