"""add precipitation

Revision ID: ea140b0a0ff1
Revises: f75c7ef2ec4c
Create Date: 2021-03-29 17:49:02.708753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea140b0a0ff1'
down_revision = 'f75c7ef2ec4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('precipitation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'precipitation')
    # ### end Alembic commands ###
